// AgriMesh API. Wraps the routing core, serves the frontend, and gives the
// admin panel its live controls. In-memory store = zero DB setup for the demo
// (swap `reports`/inventory for MongoDB later; the route logic doesn't change).
//
// Security notes (read before deploying): see SECURITY.md for the full model.
// Summary: no hardcoded secret defaults, admin sessions are random + expiring,
// rate limiting on every write/abuse-prone endpoint, CORS is allow-listed, and
// helmet sets standard security headers.
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const path = require("path");
const fs = require("fs");
const { route } = require("./core");
const { sendSMS } = require("./sms");
const { INVENTORY, NODES } = require("./graph");
const config = require("./config");
const {
  issueSession, requireAdmin, checkApiKey, safeEqual,
  generalLimiter, routeLimiter, loginLimiter, smsAbuseGuard,
  isValidCode, isValidPhone, safeError,
} = require("./middleware");

// code -> label / pesticide. Single source of truth: diseases.json (name +
// symptoms + management + pesticide, EN/HI), generated by model/gen_diseases.py.
// Local file in dev/full deploy, else the CDN mirror of this same repo — so a
// lightweight serverless deploy that ships no data files still resolves names.
// Lazy so the CDN fetch never blocks module load / cold start.
const CDN = "https://cdn.jsdelivr.net/gh/ag1170-pixel/AgriMesh@main";
let LABEL = {}, PESTICIDE = {}, DISEASES = {}, dataReady = false;
async function ensureData() {
  if (dataReady) return;
  try { DISEASES = JSON.parse(fs.readFileSync(path.join(__dirname, "diseases.json"), "utf-8")); }
  catch { DISEASES = await fetch(CDN + "/backend/diseases.json").then((r) => r.json()); }
  LABEL = Object.fromEntries(Object.entries(DISEASES).map(([c, d]) => [c, d.name_en]));
  PESTICIDE = Object.fromEntries(Object.entries(DISEASES).map(([c, d]) => [c, { en: d.pesticide_en, hi: d.pesticide_hi }]));
  dataReady = true;
}
const enrich = (r) => ({ ...r, label: LABEL[r.code] || r.code, pesticide: PESTICIDE[r.code] });

const MAX_REPORTS = 5000; // bound the in-memory store so a long-running process can't OOM
const reports = []; // { code, label, farmer, start, center, distanceKm, ts }
const logReport = (r) => {
  reports.unshift({
    code: r.code, label: LABEL[r.code] || r.code, farmer: r.farmer, start: r.start,
    center: r.center, distanceKm: r.distanceKm, ts: new Date().toISOString(),
  });
  if (reports.length > MAX_REPORTS) reports.length = MAX_REPORTS;
};

const app = express();
app.set("trust proxy", 1); // correct client IPs behind Vercel/Railway/Render for rate limiting

app.use(helmet({
  // the app is served cross-origin to CDN model/tile assets; keep CSP scoped to
  // what the frontend actually loads (see the <meta> CSP in index.html) rather
  // than locking it into brittleness here.
  contentSecurityPolicy: false,
}));

// IMPORTANT: cors({}) with no options actually defaults to Access-Control-
// Allow-Origin: * -- the opposite of "same-origin only". So when no
// allow-list is configured, skip the cors() middleware entirely: without it,
// Express adds no CORS headers at all, and the browser's own same-origin
// policy blocks cross-origin reads by default. Only wire up cors() once
// there's an explicit allow-list to enforce.
if (config.allowedOrigins.length) {
  app.use(cors({ origin: config.allowedOrigins }));
}

app.use(express.json({ limit: "1mb" })); // bound request body size
app.use(generalLimiter);

app.get("/api/health", (_req, res) => res.json({ ok: true, reports: reports.length }));

// main farmer endpoint (web app): parse payload -> route -> log.
// Optional `phone` also fires the reply SMS (mock unless a gateway is configured).
app.post("/api/route", routeLimiter, smsAbuseGuard, checkApiKey, async (req, res) => {
  if (req.body.phone && !isValidPhone(req.body.phone)) {
    return safeError(res, 400, "BAD_PHONE");
  }
  try {
    await ensureData();
    const r = route(req.body.payload, req.body.from || "web-user");
    if (r.ok) logReport(r);
    const sms = r.ok && req.body.phone ? await sendSMS(req.body.phone, r.reply) : undefined;
    res.json({ ...enrich(r), sms });
  } catch (e) {
    safeError(res, 400, "ROUTE_FAILED", e);
  }
});

// Inbound SMS webhook — a real gateway (TextBee) POSTs here when a farmer texts in,
// OR the admin "Simulate incoming SMS" button posts here. Same path either way:
// parse -> route -> log -> send the reply back over SMS to the sender.
app.post("/api/sms/inbound", routeLimiter, smsAbuseGuard, checkApiKey, async (req, res) => {
  const from = req.body.from || "unknown";
  if (from !== "unknown" && !isValidPhone(from)) return safeError(res, 400, "BAD_PHONE");
  try {
    await ensureData();
    const r = route(req.body.message ?? req.body.payload, from);
    if (r.ok) logReport(r);
    const sms = r.ok ? await sendSMS(from, r.reply) : { ok: false, skipped: "NO_ROUTE" };
    res.json({ ...enrich(r), sms });
  } catch (e) {
    safeError(res, 400, "ROUTE_FAILED", e);
  }
});

app.post("/api/admin/login", loginLimiter, (req, res) => {
  if (typeof req.body.password === "string" && safeEqual(req.body.password, config.adminPassword)) {
    return res.json({ ok: true, token: issueSession() });
  }
  return safeError(res, 401, "BAD_PASSWORD");
});

app.get("/api/admin/reports", requireAdmin, (_req, res) => res.json({ ok: true, reports }));

app.get("/api/admin/inventory", requireAdmin, async (_req, res) => {
  await ensureData();
  res.json({ ok: true, inventory: INVENTORY, labels: LABEL });
});

// live stock edit — the "watch Dijkstra re-route" demo moment
app.put("/api/admin/inventory", requireAdmin, (req, res) => {
  const { centerId, code, stockKg } = req.body;
  if (!INVENTORY[centerId]) return safeError(res, 400, "NO_CENTER");
  if (!isValidCode(code)) return safeError(res, 400, "BAD_CODE");
  const kg = Number(stockKg);
  if (!Number.isFinite(kg) || kg < 0) return safeError(res, 400, "BAD_STOCK");
  INVENTORY[centerId][code] = Math.min(kg, 100000); // sane upper bound, avoids Infinity/garbage input
  res.json({ ok: true, inventory: INVENTORY });
});

// TextBee fallback: run the exact same pipeline without a physical inbound SMS.
// If a `from` phone is given, it also fires the reply (mock unless a gateway is set),
// so the panel demonstrates the full round-trip — the reliable, phone-free demo path.
app.post("/api/admin/simulate", requireAdmin, smsAbuseGuard, async (req, res) => {
  if (req.body.from && !isValidPhone(req.body.from)) return safeError(res, 400, "BAD_PHONE");
  try {
    await ensureData();
    const r = route(req.body.payload, req.body.from || "sim");
    if (r.ok) logReport(r);
    const sms = r.ok && req.body.from ? await sendSMS(req.body.from, r.reply) : undefined;
    res.json({ ...enrich(r), sms });
  } catch (e) {
    safeError(res, 400, "ROUTE_FAILED", e);
  }
});

app.get("/api/nodes", (_req, res) => res.json(NODES)); // map needs coords

// disease detail (symptoms + management) — used by the result card and the library page
app.get("/api/disease/:code", async (req, res) => {
  if (!isValidCode(req.params.code)) return safeError(res, 400, "BAD_CODE");
  await ensureData();
  const d = DISEASES[req.params.code];
  if (!d) return safeError(res, 404, "UNKNOWN_CODE");
  res.json({ ok: true, code: req.params.code, ...d });
});
app.get("/api/diseases", async (_req, res) => { await ensureData(); res.json({ ok: true, diseases: DISEASES }); });

// serve the static frontend from one origin (no CORS headaches in demo)
app.use(express.static(path.join(__dirname, "..", "frontend")));

// last-resort handler: never leak stack traces to the client
app.use((err, _req, res, _next) => {
  console.error("[unhandled]", err);
  res.status(500).json({ ok: false, error: "INTERNAL_ERROR" });
});

// Run a real server locally (npm start); on Vercel the app is imported as a
// serverless function instead. In-memory state persists within a warm
// instance — fine for a demo; add MongoDB (HANDOFF §P3) for true persistence.
if (require.main === module) {
  app.listen(config.port, () => console.log(`AgriMesh on http://localhost:${config.port} [${config.nodeEnv}]`));
}
module.exports = app;
